# Generated by Django 5.2.16 on 2026-07-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userstatus_user_current_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='dark', max_length=10),
        ),
    ]
