# Generated by Django 5.2.16 on 2026-07-19 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'ordering': ('created_at', 'id'), 'verbose_name': 'User Status', 'verbose_name_plural': 'User Statuses'},
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('local', 'Local'), ('google', 'Google')], default='local', max_length=32, verbose_name='Auth provider'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_users', to='accounts.userstatus', verbose_name='Current status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='Email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be 3-30 characters and contain only letters, numbers, dots, hyphens, and underscores.', regex='^[A-Za-z0-9_.-]{3,30}$')], verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
