# Generated by Django 5.2.16 on 2026-07-19 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userstatus_options_alter_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
