# Generated by Django 5.2.16 on 2026-07-18 07:28

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotificationpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='email_enabled',
            field=models.BooleanField(default=notifications.models.get_default_email_enabled),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='in_app_enabled',
            field=models.BooleanField(default=notifications.models.get_default_in_app_enabled),
        ),
    ]
