# Generated by Django 5.2.16 on 2026-07-19 12:17

import django.db.models.deletion
import notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_usernotificationpreferences_email_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='usernotificationpreferences',
            options={'verbose_name': 'User Notification Preferences', 'verbose_name_plural': 'User Notification Preferences'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Read at'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='email_enabled',
            field=models.BooleanField(default=notifications.models.get_default_email_enabled, verbose_name='Email enabled'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='in_app_enabled',
            field=models.BooleanField(default=notifications.models.get_default_in_app_enabled, verbose_name='In-app enabled'),
        ),
        migrations.AlterField(
            model_name='usernotificationpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
