# Generated by Django 5.2.16 on 2026-07-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessage',
            new_name='chat_chatme_activit_343179_idx',
            old_name='chat_chatm_activity_7a2c76_idx',
        ),
    ]
