# Generated by Django 5.2.16 on 2026-07-18 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0013_joinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('AVATAR', 'Avatar'), ('BADGE', 'Badge')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='activities.activity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BadgeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=20)),
                ('shop_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='badge', to='shop.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='AvatarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_file', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('shop_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='shop.shopitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_equipped', models.BooleanField(default=False)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('shop_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='shop.shopitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'shop_item'), name='unique_user_shop_item')],
            },
        ),
    ]
