# Generated by Django 5.2.16 on 2026-07-15 17:09

import django.db.models.deletion
from django.db import migrations, models


def seed_permissions(apps, schema_editor):
    Permission = apps.get_model('activities', 'ActivityPermission')
    Permission.objects.bulk_create([
        Permission(code='checkpoints.create', name='Create checkpoints/locations'),
        Permission(code='participants.map.view', name='View participants on the map'),
    ])


def unseed_permissions(apps, schema_editor):
    apps.get_model('activities', 'ActivityPermission').objects.filter(
        code__in=['checkpoints.create', 'participants.map.view']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='activities.activitypermission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='activities.activityrole')),
            ],
        ),
        migrations.AddField(
            model_name='activityrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='activities.RolePermission', to='activities.activitypermission'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='unique_role_permission'),
        ),
        migrations.RunPython(seed_permissions, unseed_permissions),
    ]
