# Generated by Django 5.2.16 on 2026-07-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_participant_sos'),
        ('locations', '0008_meetingpoint_description_meetingpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='current_zones',
            field=models.ManyToManyField(blank=True, related_name='current_participants', to='locations.activityzone'),
        ),
    ]
