# Generated by Django 5.2.16 on 2026-07-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_joinrequest'),
        ('locations', '0010_map_object_creator_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activitypermission',
            options={'ordering': ['code'], 'verbose_name': 'Activity Permission', 'verbose_name_plural': 'Activity Permissions'},
        ),
        migrations.AlterModelOptions(
            name='activityrole',
            options={'verbose_name': 'Activity Role', 'verbose_name_plural': 'Activity Roles'},
        ),
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Join Request', 'verbose_name_plural': 'Join Requests'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Role Permission', 'verbose_name_plural': 'Role Permissions'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_activities', to='activities.activityrole', verbose_name='Default role'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ended at'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Started at'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='activitypermission',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='activitypermission',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activitypermission',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='activityrole',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='activityrole',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='activityrole',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activityrole',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='activityrole',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='activities.RolePermission', to='activities.activitypermission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='joinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='current_zones',
            field=models.ManyToManyField(blank=True, related_name='current_participants', to='locations.activityzone', verbose_name='Current zones'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Joined at'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='activities.activityrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sos_activated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SOS activated at'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='sos_active',
            field=models.BooleanField(default=False, verbose_name='SOS active'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_grants', to='activities.activitypermission', verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_grants', to='activities.activityrole', verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='scope',
            field=models.JSONField(blank=True, default=dict, verbose_name='Scope'),
        ),
    ]
