# Generated by Django 5.2.16 on 2026-07-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmarker',
            name='color',
            field=models.CharField(default='#F59E0B', max_length=20),
        ),
    ]
