# Generated by Django 5.2.16 on 2026-07-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_locationmarker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('marker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_point', to='locations.locationmarker')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
