# Generated by Django 5.2.16 on 2026-07-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_meetingpoint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='meetingpoint',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='meeting_point_end_after_start'),
        ),
    ]
