# Generated by Django 5.2.16 on 2026-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_activityzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoint',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='meetingpoint',
            name='name',
            field=models.CharField(default='Meeting point', max_length=200),
        ),
    ]
