# Generated by Django 5.2.16 on 2026-07-16 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_participant_current_zones'),
        ('locations', '0008_meetingpoint_description_meetingpoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityzone',
            name='trigger_action',
            field=models.CharField(choices=[('no_action', 'No Action'), ('on_exit', 'On Exit'), ('on_entry', 'On Entry')], default='no_action', max_length=20),
        ),
        migrations.AddField(
            model_name='activityzone',
            name='trigger_notify_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notify_zones', to='activities.activityrole'),
        ),
        migrations.AddField(
            model_name='activityzone',
            name='trigger_subject_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_zones', to='activities.activityrole'),
        ),
    ]
