# Generated by Django 5.2.16 on 2026-07-16 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0002_checkpoint_color_route_color_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutePointPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='route_points/%Y/%m/')),
                ('is_main', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkpoints.routepoint')),
            ],
        ),
        migrations.DeleteModel(
            name='RoutePhoto',
        ),
    ]
