# Generated by Django 5.2.16 on 2026-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0004_checkpointqrcode_checkpointqrcodescan'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routepoint',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
