# Generated by Django 5.2.16 on 2026-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0005_checkpoint_points_routepoint_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpointqrcode',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
