# Generated by Django 5.2.16 on 2026-07-19 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_alter_activity_options_and_more'),
        ('checkpoints', '0007_map_object_creator_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkpoint',
            options={'ordering': ['-created_at'], 'verbose_name': 'Checkpoint', 'verbose_name_plural': 'Checkpoints'},
        ),
        migrations.AlterModelOptions(
            name='checkpointphoto',
            options={'verbose_name': 'Checkpoint Photo', 'verbose_name_plural': 'Checkpoint Photos'},
        ),
        migrations.AlterModelOptions(
            name='checkpointqrcode',
            options={'ordering': ['created_at'], 'verbose_name': 'Checkpoint QR Code', 'verbose_name_plural': 'Checkpoint QR Codes'},
        ),
        migrations.AlterModelOptions(
            name='checkpointqrcodescan',
            options={'ordering': ['-scanned_at'], 'verbose_name': 'Checkpoint QR Code Scan', 'verbose_name_plural': 'Checkpoint QR Code Scans'},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-created_at'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='routepoint',
            options={'ordering': ['sequence_number'], 'verbose_name': 'Route Point', 'verbose_name_plural': 'Route Points'},
        ),
        migrations.AlterModelOptions(
            name='routepointphoto',
            options={'verbose_name': 'Route Point Photo', 'verbose_name_plural': 'Route Point Photos'},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visited_at'], 'verbose_name': 'Visit', 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='color',
            field=models.CharField(default='#9333EA', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkpoints', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='checkpoint',
            name='radius',
            field=models.FloatField(default=50.0, verbose_name='Radius'),
        ),
        migrations.AlterField(
            model_name='checkpointphoto',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkpoints.checkpoint', verbose_name='Checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpointphoto',
            name='image',
            field=models.ImageField(upload_to='checkpoints/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='checkpointphoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcode',
            name='checkpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='checkpoints.checkpoint', verbose_name='Checkpoint'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_checkpoint_qr_codes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcode',
            name='image',
            field=models.ImageField(upload_to='checkpoint_qrcodes/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcode',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcode',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcode',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR token'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcodescan',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_qr_scans', to='activities.participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcodescan',
            name='qr_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='checkpoints.checkpointqrcode', verbose_name='QR code'),
        ),
        migrations.AlterField(
            model_name='checkpointqrcodescan',
            name='scanned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Scanned at'),
        ),
        migrations.AlterField(
            model_name='route',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='activities.activity', verbose_name='Activity'),
        ),
        migrations.AlterField(
            model_name='route',
            name='color',
            field=models.CharField(default='#8B5CF6', max_length=20, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='route',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routes', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='route',
            name='main_checkpoint',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='checkpoints.checkpoint', verbose_name='Main checkpoint'),
        ),
        migrations.AlterField(
            model_name='route',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='latitude',
            field=models.FloatField(verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='longitude',
            field=models.FloatField(verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='radius',
            field=models.FloatField(default=50.0, verbose_name='Radius'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='checkpoints.route', verbose_name='Route'),
        ),
        migrations.AlterField(
            model_name='routepoint',
            name='sequence_number',
            field=models.PositiveIntegerField(verbose_name='Sequence number'),
        ),
        migrations.AlterField(
            model_name='routepointphoto',
            name='image',
            field=models.ImageField(upload_to='route_points/%Y/%m/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='routepointphoto',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is main'),
        ),
        migrations.AlterField(
            model_name='routepointphoto',
            name='route_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='checkpoints.routepoint', verbose_name='Route point'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='checkpoints.checkpoint', verbose_name='Checkpoint'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='deviation',
            field=models.FloatField(blank=True, null=True, verbose_name='Deviation'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Is manual'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_visits', to='activities.participant', verbose_name='Participant'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='route_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='checkpoints.routepoint', verbose_name='Route point'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Visited at'),
        ),
    ]
